# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Eva Richter Bat Mitzvah
email: mike@elfhome.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.evarichter.xyz" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: michaelsrichter
github_username:  michaelsrichter

# Build settings
remote_theme: SdtElectronics/jekyll-theme-antarctica
#theme: minima

template:
# date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
  date_format: "%b %d, %Y"
  widgets: colophon comment global_cmt post_meta share related_sites table_of_content
  portfolios: projects gallery
  propIcons:
    pinned: "&#x1f4cc;&#xFE0E;"

# If you want to generate website sitemap, you can set true
# sitemap: false

# Valine Comments
valine:
  appId: "GoHOdR14a6Qubobq68emQ8n2-MdYXbMMI"
  appKey: "SCxcdTzApt8RXJVrtqsDXay0"
  serverURLs: https://gohodr14.api.lncldglobal.com

collections_dir: collections
collections:
  projects:
    output: true
  gallery:
    output: true
  
projects_categories: 
  - Hardware
  - Software

related_sites:
  Jekyll | Static site generator: https://jekyllrb.com
  Source Repo | Theme antarctica: https://github.com/SdtElectronics/jekyll-theme-antarctica
  My Homepage | SdtElectronics: https://sdtelectronics.github.io/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      avatar: "assets/img/a-default.png"

# Build settings
highlighter: rouge
markdown: kramdown
kmarkdown:
  input: GFM

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
